# Additional explanations:
# 04_sejong TRIAL1(3D segmentation)


init_settings:
  input_type: 'image'  # 'video' or 'image'
  input_dir: ./data/04_20230425_sejong/01_raw_data
  base_workspace_dir: ./workspace/3D_segmentation_earthwork/04_20230425_sejong
  trial_num: 'trial1'
  image_size: null  # Set to null to maintain original size, e.g., [1280, 720]
  image_start: 0
  image_step: 120
  image_ext: '.jpg'  
  is_gps: 1 # 1 (if use gps coordinate) 0 (no gps)
  prefix: ""
  phase: 'initial'


# # new image processing settings
correspondence_settings:
#   input_type: 'video'  # 'video' or 'image'
#   input_dir: ../../../../Data/240508_SNU-Duraemidam/day2
#   base_workspace_dir: ../../../../Laboratory/02.Rapid3DReconstruction/00.workspace/Duraemidam_ChangeDetection_workspace
#   trial_num: 'trial4'
#   image_size: null   # Set to null to maintain original size, e.g., [1280, 720]
#   image_start: 60
#   image_step: 120
#   image_ext: '.jpg'
#   is_gps: 1 # 1 (if use gps coordinate) 0 (no gps)
#   prefix: "new_" # newly added images's prefix for name
#   phase: 'new_correspondence_2'

#   feature_extractor: 
#     ImageReader.single_camera: "1" 
#     ImageReader.camera_model: "OPENCV" 
#     SiftExtraction.use_gpu: "1"
#     SiftExtraction.gpu_index: "0,1" # Multi-gpu(0,1)
#     SiftExtraction.estimate_affine_shape: "0"
#     SiftExtraction.domain_size_pooling: "1" 
#     SiftExtraction.max_image_size: 2400
#     SiftExtraction.max_num_features: 15000

    
#   vocab_tree_matcher:
#     VocabTreeMatching.vocab_tree_path: '/home/wpals113/.local/share/nerfstudio/vocab_tree.fbow'    
#     VocabTreeMatching.num_images: 100
  
#   feature_matcher:
#     SiftMatching.use_gpu: "1"
#     SiftMatching.gpu_index: "1" # Multi-gpu(0,1)    
#     SiftMatching.max_ratio: 0.7
#     SiftMatching.guided_matching: "1" 

# NeRF settings

nerf_settings:    

  ns_process_options:
    # Basic Properties
    basic_properties:
      verbose: True
    # Feature Extraction
    feature_extractor:
      # max_image_size: 2400
      # max_num_features: 15000      
      # estimate_affine_shape: False
      # domain_size_pooling: True
    # Feature Matching
    feature_matcher:
      matching_method: "vocab_tree"        
      # max_ratio: 0.7
      # gpu_index: "0,1"    
      # guided_matching: True
      # tri_min_angle: "1.0"
  
  # Geo-registration
  geo_registration:
    colmap_model_path: "colmap/sparse/geo-registration/ecef"  # If is_gps: 1, check it
    align_ransac_max_error: "3.0"
    
  ns_train_options:
    nerf_model: "nerfacto"

    train_options:            
      machine.num-devices: "1"
      machine.device-type: "cuda"
      pipeline.model.camera-optimizer.mode: "off"    
      pipeline.model.predict-normals: "True"
      pipeline.datamanager.train-num-rays-per-batch: "4096"
      viewer.jpeg-quality: "100"
      viewer.make-share-url: "True"    
      vis: "viewer+tensorboard"
    
    dataparser_model: "nerfstudio-data" # GPS -> colmap / defaults: nerfstudio-data    
    dataparser_options:      
      downscale-factor: 1

    dataparser_colmap_options:
      # assume-colmap-world-coordinate-convention: "False" # COLMAP -> NeRFStudio (GPS)
      # orientation-method: "none" # NeRFStudio -> Web-GUI (GPS)
      # center-method: "none" # NeRFStudio -> Web-GUI (GPS)
      # auto-scale-poses : "False" # (GPS)
      colmap_path: "colmap/sparse/geo-registration/ecef" 
    
# ns_render_settings:
#   output_format: "images"
#   load_config: ../../../../Laboratory/02.Rapid3DReconstruction/00.workspace/Duraemidam_ChangeDetection_workspace/trial4/initial/nerf_output/ns_processed/nerfacto/2025-04-18_044615/config.yml
#   camera_path_filename: ../../../../Laboratory/02.Rapid3DReconstruction/00.workspace/Duraemidam_ChangeDetection_workspace/trial4/new_correspondence/ns_processed/camera_path.json
#   output_path: ../../../../Laboratory/02.Rapid3DReconstruction/00.workspace/Duraemidam_ChangeDetection_workspace/trial4/new_correspondence/renders



