# Sam setting
sam_checkpoint: /workspace/Laboratory/04.model/segment_anything1/sam_vit_h_4b8939.pth
model_type: vit_h
device: cuda
res_embed: 64
res_sam: 1024
threshold_cos_sim: 0.5

# grounding-dino setting
grounding_dino_config: /home/wpals113/mmdetection/configs/grounding_dino/grounding_dino_swin-l_pretrain_all.py
grounding_dino_checkpoint: /workspace/Laboratory/04.model/mmDetection/checkpoints/grounding_dino_swin-l_pretrain_all-56d69e78.pth
grounding_dino_texts: "building."
grounding_dino_pred_score_thr: 0.09
grounding_dino_iou_thr: 0.35
grounding_dino_save_dir: "/workspace/Laboratory/02.Rapid3DReconstruction/00.workspace/Naju_90m_ChangeDetection_workspace/trial5/YOLO/outputs"

initial_image_dir: /workspace/Laboratory/02.Rapid3DReconstruction/01.code/02.241030changedetection_contest/data_x1024/initial_images
new_image_dir: /workspace/Laboratory/02.Rapid3DReconstruction/01.code/02.241030changedetection_contest/data_x1024/new_images
output_dir: /workspace/Laboratory/02.Rapid3DReconstruction/01.code/02.241030changedetection_contest/workspace/outputs/data_x1024
