# Sam setting
sam_checkpoint: ../../../../Laboratory/04.model/segment_anything1/sam_vit_h_4b8939.pth
model_type: vit_h
device: cuda
res_embed: 64
res_sam: 1024
threshold_cos_sim: 0.61

# Object Detection setting
od_model: "yolo" # yolo or grounding_dino
od_target_classes: "materials. equipment. structure"
od_pred_score_thr: 0.5
od_iou_thr: 0.35
od_checkpoint: ../../../../Laboratory/02.Rapid3DReconstruction/00.workspace/Sintanjin_80m_CD_workspace/longlong_trial1/YOLO/full_1280/weights/best.pt
od_save_dir: ../../../../Laboratory/02.Rapid3DReconstruction/00.workspace/Sintanjin_80m_CD_workspace/longlong_trial1/YOLO/outputs
od_config: ../../../../Data/Sintanjin/240607_240726_Sintanjin/objectdetection_dataset/earthwork_80m_nerf_cd_pair_gps/split/data.yaml # YOLO -> data.yaml / mmdetection -> config file

# Image pair
image_pair_resize_factor: 4

image_dir: ../../../../Laboratory/02.Rapid3DReconstruction/00.workspace/Sintanjin_80m_CD_workspace/longlong_trial1/CD_PAIR/test2/nerf_cd_pair/raw
output_dir: ../../../../Laboratory/02.Rapid3DReconstruction/00.workspace/Sintanjin_80m_CD_workspace/longlong_trial1/CD_PAIR/test2/outputs/pred
